// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ParfumApp",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ParfumApp",
            targets: ["AppModule"],
            bundleIdentifier: "Chris.ParfumApp",
            teamIdentifier: "H57S947K7K",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .plane),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
		resources: [
.process("Resources")]
        )
    ]
)
